export const errorMap = {
	1: 'InvalidClientSecret',
	2: 'InvalidToken',
	3: 'EmptyFirstName',
	4: 'EmptyLastName',
	5: 'EmptyPassword',
	6: 'InvalidPassword',
	7: 'EmptyPhone',
	8: 'Số điện thoại không đúng. Bạn vui lòng kiểm tra lại.',
	9: 'EmptyEmail',
	10: 'InvalidEmail',
	11: 'EmptyBrand',
	12: 'EmptyLocation',
	13: 'InvalidRefferalCode',
	14: 'DuplicateUserName',
	15: 'Email đã tồn tại',
	16: 'Đăng nhập thất bại, vui lòng kiểm tra lại số điện thoại hoặc mật khẩu',
	17: 'No data',
	18: 'Rất tiếc, mã bạn nhập không đúng!',
	19: 'Mã bạn nhập đã được sử dụng.',
	20: 'Invalid UserId',
	21: 'Rất tiếc, bạn đã nhập đủ 10 mã. Tuy nhiên, bạn vẫn có thể tham gia khảo sát & nhận điểm từ các hoạt động khác.',
	22: 'Bạn đã nhận hết điểm từ video trong tuần.',
	23: 'Invalid Video',
	24: 'Bạn đã nhận hết điểm từ thử thách trong tuần.',
	25: 'Invalid Interactive',
	26: 'InvalidInteractiveId',
	27: 'InvalidInteractiveTitle',
	28: 'InvalidInteractiveToken',
	29: 'InvalidInteractiveEnable',
	30: 'Existed Interactive',
	31: 'InvalidActionid',
	32: 'InvalidPackCodeHeader',
	33: 'InvalidPoint',
	34: 'InvalidSurvey',
	35: 'InvalidQuestion',
	36: 'InvalidChoice',
	37: 'InvalidReferFriendHeader',
	38: 'InvalidVoucherHeader',
	39: 'EmptyVoucher',
	40: 'InvalidVoucher',
	41: 'Hết hạn mức đổi voucher này. Bạn vui lòng chọn loại voucher khác.',
	42: 'InvalidVoucherPrice',
	43: 'Mã OTP không đúng',
	44: 'InvalidTokenEmail',
	45: 'ExpiredTokenEmail',
	46: 'InvalidVerifyEmailHeader',
	47: 'Mã OTP đã hết hạn',
	48: 'InvalidSoftAgeVerificationHeader',
	49: 'InvalidRegistrationHeader',
	50: 'Bạn không đủ điểm để đổi các voucher đã chọn.',
	51: 'EmptyAvarta',
	52: 'InvalidAvartaId',
	53: 'InvalidMemberShipHeader',
	60: 'Bạn đã nhập 1 mã trong hôm nay',
	64: 'Email của bạn đã được xác thực',
}

export const errorMapping = (err) => {
	if (!err.response || !err.response.status || !errorMap[err.response.status]) {
		return 'Lỗi không xác định'
	}

	return errorMap[err.response.status]
}
