export const USER_AGE_CONFIRM = 'USER_AGE_CONFIRM'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE'
export const USER_REGISTER_FORM = 'USER_REGISTER_FORM'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'

export const USER_DETAIL_REQUEST = 'USER_DETAIL_REQUEST'
export const USER_DETAIL_SUCCESS = 'USER_DETAIL_SUCCESS'
export const USER_DETAIL_FAILURE = 'USER_DETAIL_FAILURE'
export const USER_DETAIL_RESET = 'USER_DETAIL_RESET'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAILURE = 'USER_UPDATE_PROFILE_FAILURE'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_LOGGED = 'USER_LOGGED'

export const USER_LOADING_SHOW = 'USER_LOADING_SHOW'
export const USER_LOADING_HIDE = 'USER_LOADING_HIDE'

export const CHECK_USER_REGISTER_EXISTS_REQUEST = 'CHECK_USER_REGISTER_EXISTS_REQUEST'
export const CHECK_USER_REGISTER_EXISTS_SUCCESS = 'CHECK_USER_REGISTER_EXISTS_SUCCESS'
export const CHECK_USER_REGISTER_EXISTS_FAILURE = 'CHECK_USER_REGISTER_EXISTS_FAILURE'

export const CHECK_USER_REFERAL_CODE = 'CHECK_USER_REFERAL_CODE'
